{{- if and .Values.traefik.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "freshrss.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  entryPoints:
{{- range .Values.traefik.ingressRoute.entryPoints }}
    - {{ . }}
{{- end }}
  routes:
    - match: Host(`{{ .Values.traefik.ingressRoute.host }}`) && ({{- $first := true -}}{{- range .Values.traefik.ingressRoute.pathPrefixes -}}{{- if not $first }} || {{- end -}}PathPrefix(`{{ . }}`){{- $first = false -}}{{- end -}})
      kind: Rule
{{- if .Values.traefik.ingressRoute.middlewares }}
      middlewares:
{{- range .Values.traefik.ingressRoute.middlewares }}
        - name: {{ .name }}
{{- if .namespace }}
          namespace: {{ .namespace }}
{{- end }}
{{- end }}
{{- end }}
      services:
        - name: {{ include "freshrss.fullname" . }}
          port: {{ .Values.service.port }}
{{- if .Values.traefik.ingressRoute.tls.enabled }}
  tls:
{{- if .Values.traefik.ingressRoute.tls.secretName }}
    secretName: {{ .Values.traefik.ingressRoute.tls.secretName | quote }}
{{- end }}
{{- end }}
{{- end }}
