{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "authentik.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    {{- range .Values.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - match: Host(`{{ .Values.ingressRoute.host }}`) && ({{- $first := true -}}{{- range .Values.ingressRoute.pathPrefixes -}}{{- if not $first }} || {{- end -}}PathPrefix(`{{ . }}`){{- $first = false -}}{{- end -}})
      kind: Rule
      services:
        - name: {{ include "authentik.fullname" . }}-server
          port: {{ .Values.service.port }}
  {{- if .Values.ingressRoute.tls.enabled }}
  tls:
    {{- if .Values.ingressRoute.tls.secretName }}
    secretName: {{ .Values.ingressRoute.tls.secretName | quote }}
    {{- else }}
    {}
    {{- end }}
  {{- end }}
{{- end }}
