apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentik.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/component: server
    {{- include "authentik.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
