replicaCount: 1

image:
  repository: ghcr.io/gethomepage/homepage
  tag: "v1.8.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  automount: true

rbac:
  create: true

service:
  type: ClusterIP
  port: 3000

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

env:
  HOMEPAGE_ALLOWED_HOSTS: "*"

secrets:
  existingSecret: homepage-secrets

config:
  existingConfigMap: ""

  kubernetesYaml: |
    mode: cluster
    traefik: true

  settingsYaml: |
    title: My Homepage Dashboard
    theme: dark
    iconStyle: theme
    color: slate
    language: en

    headerStyle: underlined



    logpath: /app/config/logs

    base: https://home.nserbin.com/

    hideErrors: false
    useEqualHeights: true

    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      hideVisitURL: true

    target: _blank
    showStats: true

    layout:
      Management:
        icon: mdi-view-dashboard
      Monitoring:
        icon: mdi-monitor-eye
      Networking:
        icon: mdi-wan
      News:
        icon: mdi-newspaper
      Security:
        icon: mdi-security
      Tools:
        icon: mdi-tools
      Cluster:
        icon: mdi-kubernetes

  bookmarksYaml: |
    - Courses:
        - Udemy:
            - icon: udemy.png
              abbr: U
              href: https://www.udemy.com/
              description: Udemy
        - TutorialsDojo:
            - icon: ""
              abbr: TD
              href: https://tutorialsdojo.com/
              description: Tutorials Dojo

    - Developer:
        - GitHub:
            - icon: github-light.png
              abbr: GH
              href: https://github.com/Nserbin
              description: Github Repository
        - GitLab:
            - icon: gitlab.png
              abbr: GL
              href: https://gitlab.com/
              description: Gitlab Repository
        - GitGuardian:
            - icon: ""
              abbr: GG
              href: https://dashboard.gitguardian.com/
              description: Check leaks in repositories

    - IA:
        - ChatGPT:
            - icon: chatgpt.svg
              abbr: AI
              href: https://chat.openai.com/
              description: ChatGPT
        - Gemini:
            - icon: si-googlebard
              abbr: GM
              href: https://bard.google.com/chat
              description: Gemini

    - Notes:
        - Keep:
            - icon: google-keep.svg
              abbr: GK
              href: https://keep.google.com
              description: Google Keep
        - Notion:
            - icon: notion.png
              abbr: NT
              href: https://www.notion.so/koopernic
              description: Notion

    - Social:
        - Reddit:
            - icon: reddit.png
              abbr: RE
              href: https://reddit.com/
              description: Reddit

    - Entertainment:
        - Amazon Music:
            - icon: amazon-light.png
              abbr: AMM
              href: https://music.amazon.com
              description: Amazon Music
        - YouTube:
            - icon: youtube.png
              abbr: YT
              href: https://youtube.com/
              description: YouTube
        - SoundCloud:
            - icon: mdi-soundcloud
              abbr: SC
              href: https://soundcloud.com
              description: SoundCloud
        - Netflix:
            - icon: netflix.png
              abbr: NF
              href: https://netflix.com
              description: Netflix

    - Marketplace:
        - Amazon:
            - icon: amazon-light.png
              abbr: AM
              href: https://amazon.es
              description: Amazon
        - Hagglezone:
            - icon: 
              abbr: HG
              href: https://www.hagglezon.com/
              description: Hagglezon
        - OLX:
            - icon: 
              abbr: OLX
              href: https://olx.pt
              description: SoundCloud
        - Vinted:
            - icon: 
              abbr: V
              href: https://vinted.pt
              description: Vinted

  servicesYaml: |
    - Cluster:
        - Argo CD:
            href: https://argo.nserbin.com
            siteMonitor: http://argocd-server.argocd/api/version
            description: GitOps
            server: k3s
            icon: si-argo.svg

    - Monitoring:
        - cAdvisor:
            icon: cadvisor.png
            href: https://cadvisor.nserbin.com
            siteMonitor: http://192.168.0.4:8080
            description: cAdvisor Dashboard
            server: rpi

        - Grafana:
            icon: grafana.png
            href: https://monitor.nserbin.com
            siteMonitor: http://kube-prometheus-stack-grafana.monitoring/api/health
            description: Grafana
            server: k3s

        - Prometheus:
            icon: prometheus.png
            href: https://prometheus.nserbin.com
            siteMonitor: http://kube-prometheus-stack-prometheus.monitoring:9090/-/healthy
            description: Prometheus
            server: k3s
            widget:
              type: prometheus
              url: http://kube-prometheus-stack-prometheus.monitoring:9090

        - Alertmanager:
            icon: alertmanager.png
            href: https://alerts.nserbin.com
            siteMonitor: http://kube-prometheus-stack-alertmanager.monitoring:9093/-/healthy
            description: Alertmanager
            server: k3s

        - Uptime Kuma:
            icon: uptime-kuma.png
            href: https://status.nserbin.com/
            siteMonitor: http://192.168.0.4:3001
            description: Status dashboard for all the services
            server: rpi
            widget:
              type: uptimekuma
              url: http://192.168.0.4:3001/
              slug: default

    - News:
        - FreshRSS:
            icon: freshrss.svg
            href: http://rss.nserbin.com
            description: Fresh RSS
            server: k3s
            siteMonitor: http://freshrss-freshrss.tools/
            widget:
              type: freshrss
              url: http://freshrss-freshrss.tools/
              username: ${FRESHRSS_USERNAME}
              password: ${FRESHRSS_PASSWORD}

        - Freedium:
            icon: mdi-web-sync
            href: http://free.nserbin.com
            description: Freedium Web Fork
            server: k3s
            #siteMonitor: http://freedium-web

    - Networking:
        - Pi-hole:
            icon: pi-hole.svg
            href: https://pihole.nserbin.com/admin
            siteMonitor: http://192.168.0.4:83/
            description: Pi-hole DNS
            server: rpi
              

        - Traefik:
            icon: traefik.svg
            href: https://traefik.nserbin.com/dashboard/
            siteMonitor: http://traefik.traefik:9000/ping
            description: Traefik
            server: k3s

    - Management:
        - Portainer:
            icon: portainer.svg
            href: https://portainer.nserbin.com/
            siteMonitor: http://192.168.0.4:9000/
            description: Portainer
            server: rpi

    - Tools:

        - Grimoire:
            icon: grimoire.png
            href: https://bookmarks.nserbin.com/
            #siteMonitor: http://192.168.0.4:8082
            description: Bookmarks
            server: k3s
    
        - DocuSeal:
            icon: docuseal.png
            href: https://docs.nserbin.com/
            description: Sign documents
            server: rpi

        - Watchtower:
            icon: watchtower.svg
            href: http://192.168.0.4:8081/
            siteMonitor: http://192.168.0.4:8081/
            description: Service to pull images
            server: rpi

        - SSH:
            icon: shell.svg
            href: https://ssh-tunnel.nserbin.com/
            description: SSH Tunnel to RPi
            server: rpi

        - Vault:
            icon: filebrowser.png
            href: https://vault.nserbin.com/
            siteMonitor: http://192.168.0.4:8082
            description: FileBrowser
            server: rpi
            widget:
              type: filebrowser
              #url: http://192.168.0.4:8082
              url: https://vault.nserbin.com
              username: ${FILEBROWSER_USERNAME}
              password: ${FILEBROWSER_PASSWORD}

    - Security:
        - Bitwarden:
            icon: bitwarden.svg
            href: https://btw.nserbin.com
            siteMonitor: http://192.168.0.4:8484
            description: Bitwarden
            server: rpi

  widgetsYaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true

    - resources:
        label: Uptime
        uptime: true

    - datetime:
        text_size: l
        locale: es
        format:
          timeStyle: short
          hourCycle: h23
          dateStyle: short

    - search:
        provider: duckduckgo
        target: _blank

  dockerYaml: ""
  customCss: ""
  customJs: ""

persistence:
  logs:
    enabled: false
    size: 1Gi
    storageClassName: ""

traefik:
  ingressRoute:
    enabled: true
    entryPoints:
      - web
    host: "home.nserbin.com"
    tls:
      enabled: true
      secretName: ""
    stickySessions:
      enabled: false
      cookie:
        name: "homepage_sticky"
        secure: true
        httpOnly: true
        sameSite: "none"

dnsPolicy: ClusterFirst
# dnsConfig:
#   options:
#     - name: ndots
#       value: "1"
#     - name: single-request-reopen
#       value: ""