{{- if .Values.externalTargets.enabled -}}
{{- $ns := .Values.externalTargets.namespace | default .Release.Namespace -}}
{{- $rl := .Values.externalTargets.releaseLabel -}}
{{- range $t := .Values.externalTargets.targets }}
{{- if not $t.ip }}
{{- fail (printf "externalTargets.targets[%s].ip is required" $t.name) }}
{{- end }}
{{- range $e := $t.exporters }}
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ printf "%s-%s" $t.name $e.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $ns }}
  labels:
    kubernetes.io/service-name: {{ printf "%s-%s" $t.name $e.name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ printf "external-%s" $t.name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: {{ $e.name }}
    {{- if and $rl $rl.key $rl.value }}
    {{ $rl.key }}: {{ $rl.value | quote }}
    {{- end }}
addressType: IPv4
ports:
  - name: metrics
    port: {{ $e.port }}
    protocol: TCP
endpoints:
  - addresses:
      - {{ $t.ip | quote }}
    conditions: {}
    hostname: {{ printf "%s-%s" $t.name $e.name | quote }}      
---
{{- end }}
{{- end }}
{{- end }}
