{{- if .Values.externalTargets.enabled -}}
{{- $ns := .Values.externalTargets.namespace | default .Release.Namespace -}}
{{- $rl := .Values.externalTargets.releaseLabel -}}
{{- range $t := .Values.externalTargets.targets }}
{{- range $e := $t.exporters }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $t.name $e.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: {{ printf "external-%s" $t.name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: {{ $e.name }}
    {{- if and $rl $rl.key $rl.value }}
    {{ $rl.key }}: {{ $rl.value | quote }}
    {{- end }}
spec:
  # Headless para que apunte a Endpoints manuales
  clusterIP: None
  ports:
    - name: metrics
      port: {{ $e.port }}
      targetPort: {{ $e.port }}
      protocol: TCP
---
{{- end }}
{{- end }}
{{- end }}
