{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freedium.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: {{ .Values.postgresql.port }}
      targetPort: postgres
{{- end }}
