apiVersion: v1
kind: Service
metadata:
  name: {{ include "grimoire.fullname" . }}
  labels:
    {{- include "grimoire.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "grimoire.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
