apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: {{ .Values.alerting.namespace | default "monitoring" }}
  labels:
    app.kubernetes.io/name: alertmanager-templates
    app.kubernetes.io/part-of: kube-prometheus-stack
data:
{{- $files := .Files.Glob "files/alertmanager-templates/*.tmpl" }}
{{- if not $files }}
  _README.txt: "No templates found under files/alertmanager-templates/*.tmpl"
{{- else }}
{{- range $path, $file := $files }}
  {{ base $path }}: |-
{{ $file | toString | indent 4 }}
{{- end }}
{{- end }}
