replicaCount: 1
image:
  repository: ghcr.io/nserbin/freedium-web
  tag: sha-caf4cd5
  pullPolicy: IfNotPresent
caddy:
  enabled: true
  image:
    repository: ghcr.io/nserbin/freedium-caddy
    tag: sha-caf4cd5
    pullPolicy: IfNotPresent
  port: 80
  logLevel: INFO
service:
  type: ClusterIP
  port: 80
ingressRoute:
  enabled: true
  entryPoints:
    - web
  host: free.nserbin.com
  pathPrefixes:
    - /
  tls:
    enabled: false
    secretName: ""
# Separaci√≥n REAL de secretos (esto arregla caos y evita pisadas)
secrets:
  appExistingSecret: freedium-app-secret
  postgresExistingSecret: freedium-postgres-secret
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 768Mi
config:
  HOST_ADDRESS: "https://free.nserbin.com"
  LOG_LEVEL_NAME: "INFO"
  MORE_LOGS: "false"
  DISABLE_EXTERNAL_DOCS: "true"
  TIMEOUT: "38"
  REQUEST_TIMEOUT: "12"
  WORKER_TIMEOUT: "85"
  CACHE_LIFE_TIME: "18000"
  HOME_PAGE_MAX_POSTS: "45"
  ENABLE_ADS_BANNER: "false"
  REDIS_TIMEOUT: "1.75"
postgresql:
  enabled: true
  image: "postgres:16.3-alpine3.20"
  serviceName: "postgres"
  port: 5432
  storage:
    size: 2Gi
redis:
  enabled: true
  image: "docker.dragonflydb.io/dragonflydb/dragonfly"
  serviceName: "redis"
  port: 6379
  storage:
    size: 1Gi
