apiVersion: v2
name: metallb
description: MetalLB + Homelab Config (IPAddressPools + L2Advertisements)
type: application
version: 0.1.0

dependencies:
  - name: metallb
    repository: "https://metallb.github.io/metallb"
    version: "0.15.3"
    alias: metallb
