apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freedium.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freedium.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "freedium.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "freedium.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        {{- if .Values.caddy.enabled }}
        - name: caddy
          image: "{{ .Values.caddy.image.repository }}:{{ .Values.caddy.image.tag }}"
          imagePullPolicy: {{ .Values.caddy.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.caddy.port }}
              name: http
          volumeMounts:
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
        {{- end }}

        - name: freedium
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 7080
              name: app
          envFrom:
            - configMapRef:
                name: {{ include "freedium.fullname" . }}-config
            - secretRef:
                name: {{ .Values.secrets.appExistingSecret }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: caddyfile
          configMap:
            name: {{ include "freedium.fullname" . }}-caddy
