apiVersion: v1
kind: Service
metadata:
  name: {{ include "freedium.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freedium.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "freedium.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
