{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: postgres
    {{- include "authentik.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgresql.port }}
      targetPort: postgres
{{- end }}
