apiVersion: v2
name: monitoring
description: Prometheus + Grafana (kube-prometheus-stack)
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: "80.5.0"
    repository: "https://prometheus-community.github.io/helm-charts"
