{{- if not .Values.config.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "homepage.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  kubernetes.yaml: |
{{ .Values.config.kubernetesYaml | indent 4 }}
  settings.yaml: |
{{ .Values.config.settingsYaml | indent 4 }}
  bookmarks.yaml: |
{{ .Values.config.bookmarksYaml | indent 4 }}
  services.yaml: |
{{ .Values.config.servicesYaml | indent 4 }}
  widgets.yaml: |
{{ .Values.config.widgetsYaml | indent 4 }}
  docker.yaml: |
{{ .Values.config.dockerYaml | indent 4 }}
  custom.css: |
{{ .Values.config.customCss | indent 4 }}
  custom.js: |
{{ .Values.config.customJs | indent 4 }}
{{- end }}
