{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "homepage.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "homepage.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
