{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "freshrss.fullname" . }}-mysql
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: 3306
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mysql
{{- end }}
