{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "freshrss.fullname" . }}-mysql
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "freshrss.fullname" . }}-mysql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}

          envFrom:
            - secretRef:
                name: {{ required "mysql.existingSecret is required (you manage it locally)" .Values.mysql.existingSecret }}

          ports:
            - name: mysql
              containerPort: 3306

          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 6

          volumeMounts:
            - name: mysqldata
              mountPath: /var/lib/mysql

  {{- if .Values.mysql.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: mysqldata
      spec:
        accessModes:
          {{- toYaml .Values.mysql.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size }}
        {{- if .Values.mysql.persistence.storageClass }}
        storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
        {{- end }}
  {{- end }}
{{- end }}
