apiVersion: v1
kind: Service
metadata:
  name: it-tools
  labels:
    app.kubernetes.io/name: it-tools
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: it-tools
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
