apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yopass.fullname" . }}
  labels:
{{ include "yopass.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "yopass.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "yopass.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: yopass
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
{{ toYaml .Values.yopass.args | indent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources.yopass | indent 12 }}

        - name: yopass-memcached
          image: "{{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag }}"
          imagePullPolicy: {{ .Values.memcached.image.pullPolicy }}
          args:
{{ toYaml .Values.memcached.args | indent 12 }}
          ports:
            - name: memcached
              containerPort: 11211
              protocol: TCP
          resources:
{{ toYaml .Values.resources.memcached | indent 12 }}

{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}

{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}

{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
