{{- range .Values.l2Advertisements }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ required "l2Advertisements[].name is required" .name }}
  namespace: {{ .namespace | default "metallb-system" }}
spec:
  {{- if .ipAddressPools }}
  ipAddressPools:
  {{- range $p := .ipAddressPools }}
    - {{ $p }}
  {{- end }}
  {{- end }}
---
{{- end }}
