{{- if .Values.prometheusScraper.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheusScraper.serviceAccountName }}
  namespace: {{ .Values.prometheusScraper.namespace }}
{{- end }}
